name: CI

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        if: github.event.pull_request.merged == true
        run: echo ${{github.event.pull_request.merged}}

      - name: Evaluate Sanitized Branch Name
        if: github.event.pull_request.merged == true
        run: |
          echo "This Github REF: $GITHUB_HEAD_REF"
        
          SANITIZED_BRANCH_NAME="${GITHUB_HEAD_REF//[^[:alnum:]]/-}"
          SANITIZED_BRANCH_NAME=$(echo "$SANITIZED_BRANCH_NAME" | tr '[:upper:]' '[:lower:]')
          echo "SANITIZED_BRANCH_NAME=$SANITIZED_BRANCH_NAME" >> "$GITHUB_ENV"
          echo "TICKET_KEY=${SANITIZED_BRANCH_NAME##*-}" >> "$GITHUB_ENV"

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          permission-contents: write
          permission-metadata: read
          owner: ${{ github.repository_owner }}

      - name: Run a one-line script
        run: echo "${{ steps.app-token.outputs.token }}! and ${{ github.event.pull_request.title }}"
          

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: hdinh95/api-client
          event-type: ipp-merge-pr
          client-payload: '{"pr_name": "ITU - 999 ${{ github.event.pull_request.title }}", "reports": {"name": "Example Report","report-url": "https://example.com/report"}}'
